spring:
  profiles:
    active: '@spring.profiles.active@'
server:
  error:
    include-message: always
jwt:
  http:
    request:
      header: Authorization
  token:
    expiration:
      in:
        seconds: 86400
  signing:
    key:
      secret: ${MONOPOLY_APP_JWT_SECRET}

---
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  flyway:
    enabled: false

---
spring:
    profiles: prod
    datasource:
      url: jdbc:postgresql://${POSTGRES_URL}:${POSTGRES_PORT}/monopolydb
      username: ${MONOPOLY_APP_DB_USER}
      password: ${MONOPOLY_APP_DB_PASSWORD}
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: validate
    sql:
      init:
        mode: never
