INSERT INTO property (
    name,
    cost,
    color,
    rent_for_site,
    rent_for_color_group,
    rent_one_house_or_railroad,
    rent_two_house_or_railroad,
    rent_three_house_or_railroad,
    rent_four_house_or_railroad,
    rent_hotel,
    building_cost,
    mortgage_value,
    unmortgage_value,
    is_regular_property,
    is_railroad,
    is_utility,
    board_position_order
) VALUES (
    'Atlantic Avenue',
    260,
    'yellow',
    22,
    44,
    110,
    330,
    800,
    975,
    1150,
    150,
    130,
    143,
    true,
    false,
    false,
    19
 );
