INSERT INTO property (
    name,
    cost,
    color,
    rent_for_site,
    rent_for_color_group,
    rent_one_house_or_railroad,
    rent_two_house_or_railroad,
    rent_three_house_or_railroad,
    rent_four_house_or_railroad,
    rent_hotel,
    building_cost,
    mortgage_value,
    unmortgage_value,
    is_regular_property,
    is_railroad,
    is_utility
) VALUES (
    'Mediterranean Avenue',
    60,
    'dark purple',
    2,
    4,
    10,
    30,
    90,
    160,
    250,
    50,
    30,
    33,
    true,
    false,
    false
);

INSERT INTO property (
    name,
    cost,
    color,
    rent_for_site,
    rent_for_color_group,
    rent_one_house_or_railroad,
    rent_two_house_or_railroad,
    rent_three_house_or_railroad,
    rent_four_house_or_railroad,
    rent_hotel,
    building_cost,
    mortgage_value,
    unmortgage_value,
    is_regular_property,
    is_railroad,
    is_utility
) VALUES (
     'Baltic Avenue',
     60,
     'dark purple',
     4,
     8,
     20,
     60,
     180,
     320,
     450,
     50,
     30,
     33,
     true,
     false,
     false
);

INSERT INTO property (
    name,
    cost,
    rent_one_house_or_railroad,
    rent_two_house_or_railroad,
    rent_three_house_or_railroad,
    rent_four_house_or_railroad,
    mortgage_value,
    unmortgage_value,
    is_regular_property,
    is_railroad,
    is_utility
) VALUES (
    'Reading Railroad',
    200,
    25,
    50,
    100,
    200,
    100,
    110,
    false,
    true,
    false
);

INSERT INTO property (
    name,
    cost,
    color,
    rent_for_site,
    rent_for_color_group,
    rent_one_house_or_railroad,
    rent_two_house_or_railroad,
    rent_three_house_or_railroad,
    rent_four_house_or_railroad,
    rent_hotel,
    building_cost,
    mortgage_value,
    unmortgage_value,
    is_regular_property,
    is_railroad,
    is_utility
) VALUES (
    'Oriental Avenue',
    100,
    'light blue',
    6,
    12,
    30,
    90,
    270,
    400,
    550,
    50,
    50,
    55,
    true,
    false,
    false
);

INSERT INTO property (
    name,
    cost,
    color,
    rent_for_site,
    rent_for_color_group,
    rent_one_house_or_railroad,
    rent_two_house_or_railroad,
    rent_three_house_or_railroad,
    rent_four_house_or_railroad,
    rent_hotel,
    building_cost,
    mortgage_value,
    unmortgage_value,
    is_regular_property,
    is_railroad,
    is_utility
) VALUES (
    'Vermont Avenue',
    100,
    'light blue',
    6,
    12,
    30,
    90,
    270,
    400,
    550,
    50,
    50,
    55,
    true,
    false,
    false
);

INSERT INTO property (
    name,
    cost,
    color,
    rent_for_site,
    rent_for_color_group,
    rent_one_house_or_railroad,
    rent_two_house_or_railroad,
    rent_three_house_or_railroad,
    rent_four_house_or_railroad,
    rent_hotel,
    building_cost,
    mortgage_value,
    unmortgage_value,
    is_regular_property,
    is_railroad,
    is_utility
) VALUES (
    'Connecticut Avenue',
    120,
    'light blue',
    8,
    16,
    40,
    100,
    300,
    450,
    600,
    50,
    60,
    66,
    true,
    false,
    false
);

INSERT INTO property (
    name,
    cost,
    color,
    rent_for_site,
    rent_for_color_group,
    rent_one_house_or_railroad,
    rent_two_house_or_railroad,
    rent_three_house_or_railroad,
    rent_four_house_or_railroad,
    rent_hotel,
    building_cost,
    mortgage_value,
    unmortgage_value,
    is_regular_property,
    is_railroad,
    is_utility
) VALUES (
    'St. Charles Place',
    140,
    'light purple',
    10,
    20,
    50,
    150,
    450,
    625,
    750,
    100,
    70,
    77,
    true,
    false,
    false
);

INSERT INTO property (
    name,
    cost,
    mortgage_value,
    unmortgage_value,
    is_regular_property,
    is_railroad,
    is_utility
) VALUES (
    'Electric Company',
    150,
    75,
    83,
    false,
    false,
    true
);

INSERT INTO property (
    name,
    cost,
    color,
    rent_for_site,
    rent_for_color_group,
    rent_one_house_or_railroad,
    rent_two_house_or_railroad,
    rent_three_house_or_railroad,
    rent_four_house_or_railroad,
    rent_hotel,
    building_cost,
    mortgage_value,
    unmortgage_value,
    is_regular_property,
    is_railroad,
    is_utility
) VALUES (
    'States Avenue',
    140,
    'light purple',
    10,
    20,
    50,
    150,
    450,
    625,
    750,
    100,
    70,
    77,
    true,
    false,
    false
);

INSERT INTO property (
    name,
    cost,
    color,
    rent_for_site,
    rent_for_color_group,
    rent_one_house_or_railroad,
    rent_two_house_or_railroad,
    rent_three_house_or_railroad,
    rent_four_house_or_railroad,
    rent_hotel,
    building_cost,
    mortgage_value,
    unmortgage_value,
    is_regular_property,
    is_railroad,
    is_utility
) VALUES (
    'Virginia Avenue',
    160,
    'light purple',
    12,
    24,
    60,
    180,
    500,
    700,
    900,
    100,
    80,
    88,
    true,
    false,
    false
);

INSERT INTO property (
    name,
    cost,
    rent_one_house_or_railroad,
    rent_two_house_or_railroad,
    rent_three_house_or_railroad,
    rent_four_house_or_railroad,
    mortgage_value,
    unmortgage_value,
    is_regular_property,
    is_railroad,
    is_utility
) VALUES (
    'Pennsylvania Railroad',
    200,
    25,
    50,
    100,
    200,
    100,
    110,
    false,
    true,
    false
);

INSERT INTO property (
    name,
    cost,
    color,
    rent_for_site,
    rent_for_color_group,
    rent_one_house_or_railroad,
    rent_two_house_or_railroad,
    rent_three_house_or_railroad,
    rent_four_house_or_railroad,
    rent_hotel,
    building_cost,
    mortgage_value,
    unmortgage_value,
    is_regular_property,
    is_railroad,
    is_utility
) VALUES (
    'St. James Place',
    180,
    'orange',
    14,
    28,
    70,
    200,
    550,
    750,
    950,
    100,
    90,
    99,
    true,
    false,
    false
);

INSERT INTO property (
    name,
    cost,
    color,
    rent_for_site,
    rent_for_color_group,
    rent_one_house_or_railroad,
    rent_two_house_or_railroad,
    rent_three_house_or_railroad,
    rent_four_house_or_railroad,
    rent_hotel,
    building_cost,
    mortgage_value,
    unmortgage_value,
    is_regular_property,
    is_railroad,
    is_utility
) VALUES (
    'Tennessee Avenue',
    180,
    'orange',
    14,
    28,
    70,
    200,
    550,
    750,
    950,
    100,
    90,
    99,
    true,
    false,
    false
);

INSERT INTO property (
    name,
    cost,
    color,
    rent_for_site,
    rent_for_color_group,
    rent_one_house_or_railroad,
    rent_two_house_or_railroad,
    rent_three_house_or_railroad,
    rent_four_house_or_railroad,
    rent_hotel,
    building_cost,
    mortgage_value,
    unmortgage_value,
    is_regular_property,
    is_railroad,
    is_utility
) VALUES (
    'New York Avenue',
    200,
    'orange',
    16,
    32,
    80,
    220,
    600,
    800,
    1000,
    100,
    100,
    110,
    true,
    false,
    false
);

INSERT INTO property (
    name,
    cost,
    color,
    rent_for_site,
    rent_for_color_group,
    rent_one_house_or_railroad,
    rent_two_house_or_railroad,
    rent_three_house_or_railroad,
    rent_four_house_or_railroad,
    rent_hotel,
    building_cost,
    mortgage_value,
    unmortgage_value,
    is_regular_property,
    is_railroad,
    is_utility
) VALUES (
    'Kentucky Avenue',
    220,
    'red',
    18,
    36,
    90,
    250,
    700,
    875,
    1050,
    150,
    110,
    121,
    true,
    false,
    false
);

INSERT INTO property (
    name,
    cost,
    color,
    rent_for_site,
    rent_for_color_group,
    rent_one_house_or_railroad,
    rent_two_house_or_railroad,
    rent_three_house_or_railroad,
    rent_four_house_or_railroad,
    rent_hotel,
    building_cost,
    mortgage_value,
    unmortgage_value,
    is_regular_property,
    is_railroad,
    is_utility
) VALUES (
    'Indiana Avenue',
    220,
    'red',
    18,
    36,
    90,
    250,
    700,
    875,
    1050,
    150,
    110,
    121,
    true,
    false,
    false
);

INSERT INTO property (
    name,
    cost,
    color,
    rent_for_site,
    rent_for_color_group,
    rent_one_house_or_railroad,
    rent_two_house_or_railroad,
    rent_three_house_or_railroad,
    rent_four_house_or_railroad,
    rent_hotel,
    building_cost,
    mortgage_value,
    unmortgage_value,
    is_regular_property,
    is_railroad,
    is_utility
) VALUES (
    'Illinois Avenue',
    240,
    'red',
    20,
    40,
    100,
    300,
    750,
    925,
    1100,
    150,
    120,
    132,
    true,
    false,
    false
);

INSERT INTO property (
    name,
    cost,
    rent_one_house_or_railroad,
    rent_two_house_or_railroad,
    rent_three_house_or_railroad,
    rent_four_house_or_railroad,
    mortgage_value,
    unmortgage_value,
    is_regular_property,
    is_railroad,
    is_utility
) VALUES (
    'B&O Railroad',
    200,
    25,
    50,
    100,
    200,
    100,
    110,
    false,
    true,
    false
);

INSERT INTO property (
    name,
    cost,
    color,
    rent_for_site,
    rent_for_color_group,
    rent_one_house_or_railroad,
    rent_two_house_or_railroad,
    rent_three_house_or_railroad,
    rent_four_house_or_railroad,
    rent_hotel,
    building_cost,
    mortgage_value,
    unmortgage_value,
    is_regular_property,
    is_railroad,
    is_utility
) VALUES (
    'Ventnor Avenue',
    260,
    'yellow',
    22,
    44,
    110,
    330,
    800,
    975,
    1150,
    150,
    130,
    143,
    true,
    false,
    false
);

INSERT INTO property (
    name,
    cost,
    mortgage_value,
    unmortgage_value,
    is_regular_property,
    is_railroad,
    is_utility
) VALUES (
    'Water Works',
    150,
    75,
    83,
    false,
    false,
    true
);

INSERT INTO property (
    name,
    cost,
    color,
    rent_for_site,
    rent_for_color_group,
    rent_one_house_or_railroad,
    rent_two_house_or_railroad,
    rent_three_house_or_railroad,
    rent_four_house_or_railroad,
    rent_hotel,
    building_cost,
    mortgage_value,
    unmortgage_value,
    is_regular_property,
    is_railroad,
    is_utility
) VALUES (
    'Marvin Gardens',
    280,
    'yellow',
    24,
    48,
    120,
    360,
    850,
    1025,
    1200,
    150,
    140,
    154,
    true,
    false,
    false
);

INSERT INTO property (
    name,
    cost,
    color,
    rent_for_site,
    rent_for_color_group,
    rent_one_house_or_railroad,
    rent_two_house_or_railroad,
    rent_three_house_or_railroad,
    rent_four_house_or_railroad,
    rent_hotel,
    building_cost,
    mortgage_value,
    unmortgage_value,
    is_regular_property,
    is_railroad,
    is_utility
) VALUES (
    'Pacific Avenue',
    300,
    'green',
    26,
    52,
    130,
    390,
    900,
    1100,
    1275,
    200,
    150,
    165,
    true,
    false,
    false
);

INSERT INTO property (
    name,
    cost,
    color,
    rent_for_site,
    rent_for_color_group,
    rent_one_house_or_railroad,
    rent_two_house_or_railroad,
    rent_three_house_or_railroad,
    rent_four_house_or_railroad,
    rent_hotel,
    building_cost,
    mortgage_value,
    unmortgage_value,
    is_regular_property,
    is_railroad,
    is_utility
) VALUES (
    'North Carolina Avenue',
    300,
    'green',
    26,
    52,
    130,
    390,
    900,
    1100,
    1275,
    200,
    150,
    165,
    true,
    false,
    false
);

INSERT INTO property (
    name,
    cost,
    color,
    rent_for_site,
    rent_for_color_group,
    rent_one_house_or_railroad,
    rent_two_house_or_railroad,
    rent_three_house_or_railroad,
    rent_four_house_or_railroad,
    rent_hotel,
    building_cost,
    mortgage_value,
    unmortgage_value,
    is_regular_property,
    is_railroad,
    is_utility
) VALUES (
    'Pennsylvania Avenue',
    320,
    'green',
    28,
    56,
    150,
    450,
    1000,
    1200,
    1400,
    200,
    160,
    176,
    true,
    false,
    false
);

INSERT INTO property (
    name,
    cost,
    rent_one_house_or_railroad,
    rent_two_house_or_railroad,
    rent_three_house_or_railroad,
    rent_four_house_or_railroad,
    mortgage_value,
    unmortgage_value,
    is_regular_property,
    is_railroad,
    is_utility
) VALUES (
    'Short Line Railroad',
    200,
    25,
    50,
    100,
    200,
    100,
    110,
    false,
    true,
    false
);

INSERT INTO property (
    name,
    cost,
    color,
    rent_for_site,
    rent_for_color_group,
    rent_one_house_or_railroad,
    rent_two_house_or_railroad,
    rent_three_house_or_railroad,
    rent_four_house_or_railroad,
    rent_hotel,
    building_cost,
    mortgage_value,
    unmortgage_value,
    is_regular_property,
    is_railroad,
    is_utility
) VALUES (
    'Park Place',
    350,
    'dark blue',
    35,
    70,
    175,
    500,
    1100,
    1300,
    1500,
    200,
    175,
    193,
    true,
    false,
    false
);

INSERT INTO property (
    name,
    cost,
    color,
    rent_for_site,
    rent_for_color_group,
    rent_one_house_or_railroad,
    rent_two_house_or_railroad,
    rent_three_house_or_railroad,
    rent_four_house_or_railroad,
    rent_hotel,
    building_cost,
    mortgage_value,
    unmortgage_value,
    is_regular_property,
    is_railroad,
    is_utility
) VALUES (
    'Boardwalk',
    400,
    'dark blue',
    50,
    100,
    200,
    600,
    1400,
    1700,
    2000,
    200,
    200,
    220,
    true,
    false,
    false
);
